name: Swift

on:
  push

jobs:
  build:

    runs-on: ios

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: arch -x86_64 swift build -v
    - name: Run tests
      run: arch -x86_64 swift test -v
