name: Swift

on:
  push

jobs:
  build:

    runs-on: ios

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift package clean; swift build
    - name: Run tests
      run: swift test